Setup-desktop version
dhirajsingha143/Portfolio pull request #4
Opened 2022-12-08 20:16 UTC by dhirajsingha143

- Update the README file with recent changes.
- Increase compatibility of portfolio site on bigger screens.

2022-12-08 20:33 UTC, dhirajsingha143 commented
- Linter errors resolve.

2022-12-08 21:54 UTC, iambenkis requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @dhirajsingha143  👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project, but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark: 

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Required Changes ♻️

- [ ] You should stick to the design as much as possible (e.g. font, colours, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). Kindly make sure you respect the width of the sections :+1: . _**You will learn more as you look at the comments below.**_

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me `@iambenkis` in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 21:54 UTC, iambenkis commented on index.html
>        </nav>
- [ ] Make sure the space between the `logo` and the `nav-list` should stick to the Figma design, It's an important part of the requirement. Kindly fix that. :+1: 

Your design

![Screenshot from 2022-12-08 23-14-30](https://user-images.githubusercontent.com/80458199/206572310-6ad6d292-8908-48b1-baa9-2817ad8cd508.png)

Figma Design

![Screenshot from 2022-12-08 23-16-10](https://user-images.githubusercontent.com/80458199/206572370-c49e3810-b756-4ac0-95c1-246651020e76.png)

2022-12-08 21:54 UTC, iambenkis commented on index.html
>          <p class="contact-text">
- [ ] Good job for this job you did :+1: , however , make sure the contact `section` fill all the width of the screen in the `desktop` version as it is represented in the Figma design. Kindly remove the space in `Red`. :100: on the picture below

Your design 

![Screenshot from 2022-12-08 22-59-31](https://user-images.githubusercontent.com/80458199/206574268-48c071c4-cfd4-42aa-bee4-1357310d5e88.png)

2022-12-08 21:54 UTC, iambenkis commented on index.html
> +            </p>
- [ ] Good job for this job you did :+1: , however , make sure the  ` about section` fill all the width of the screen in the `desktop` version as it is represented in the Figma design. Kindly remove the space in `Red`. :100: on the picture below

Your design 

![Screenshot from 2022-12-08 23-11-43](https://user-images.githubusercontent.com/80458199/206574781-cdd675ec-cfc8-431f-bbe5-50b2c6700c8d.png)

2022-12-09 04:59 UTC, dhirajsingha143 commented
- Resolve Navigation spacing.
- Resolve spacing issues (Now compatible with screens up to 4000px width)

2022-12-09 05:26 UTC, Tadesse-Alemayehu approved these changes
### Hi @dhirajsingha143 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![68747470733a2f2f6669636f666f72756d732e6d796669636f2e636f6d2f74352f696d6167652f736572766572706167652f696d6167652d69642f343932363069463839303835363833444139334135422f696d6167652d73697](https://user-images.githubusercontent.com/69077061/200411711-6e741427-6e46-4354-932f-f1445ecc09bd.gif)

## Highlights
 - [ ] Good job making the changes requested by the previous code reviewer. 🙏
 - [ ]  Correct GitHub Flow 👍🏾
 - [ ]  Good commit history 🥇
 - [ ]  Good PR title/description 💯
 - [ ]  All linters passed 🥇
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 05:40 UTC, merged